name: syrah
repository: https://github.com/benyaminsalimi/syrah-proxy

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze --fatal-infos=false .
    description: Run dart analyze in all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  build_runner:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner in packages that need it
    packageFilters:
      dependsOn: build_runner

  generate:
    description: Run code generation (freezed, json_serializable, etc.)
    run: melos run build_runner

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  get:
    run: melos exec -- flutter pub get
    description: Get dependencies for all packages
