# Analysis options for syrah_app
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat deprecation warnings as info, not errors
    deprecated_member_use: info
    unnecessary_import: info

linter:
  rules:
    # Allow print statements during development
    avoid_print: false
