# Use lints package for pure Dart packages (not flutter_lints)
include: package:lints/recommended.yaml

analyzer:
  errors:
    # Treat these as warnings, not errors
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    avoid_print: false
